In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv(r'Projeto Base\data\penguins.csv')
df.head()

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [3]:
dfg = (
    df
    .groupby(['island', 'species'])
    ['body_mass_g'].mean()
    .reset_index()
    .round(2)
    .rename(columns={
        'island': 'Ilha'
        , 'species': 'Espécies'
        , 'body_mass_g': 'Massa (g)'
    })
)

dfg.head()

        Ilha   Espécies  Massa (g)
0     Biscoe     Adelie    3709.66
1     Biscoe     Gentoo    5076.02
2      Dream     Adelie    3688.39
3      Dream  Chinstrap    3733.09
4  Torgersen     Adelie    3706.37

In [4]:
fig = (
    px.bar(
        dfg
        , x="Ilha"
        , y="Massa (g)"
        , color='Espécies'
        , title="Peso Médio dos Pinguins por ilha"
        , barmode="group"
    )
)

fig.show()